bunch-o-updates

diff --git a/bin/ontime-commit b/bin/ontime-commit
--- a/bin/ontime-commit
+++ b/bin/ontime-commit
@@ -14,6 +14,10 @@ if ! is-repo; then
 fi
 
 duedate=$(date --date="$1" +'%s')
+if [ -z "$duedate" ]; then
+    echo "$1: could not parse date" >&2
+    exit 1
+fi
 
 ontime=""
 while read logstr; do
@@ -22,7 +26,8 @@ while read logstr; do
       	 ontime="$logstr"
 	 break;
       fi
-done < <( git log --full-history --pretty="format:%H %ct %ce" | sort -r -k 2 )
+done < <( git log --full-history --pretty="format:%H %ct %ce" 2>/dev/null | grep -v '^#' | sort -r -k 2 )
+
 if [ ! -z "$ontime" ]; then
     echo "$ontime"
 else
diff --git a/bin/switch_to_review_branch b/bin/switch_to_review_branch
--- a/bin/switch_to_review_branch
+++ b/bin/switch_to_review_branch
@@ -1,4 +1,4 @@
-#!/usr/bin/bash
+#!/bin/bash
 
 path="$1"
 duedate="$2"
@@ -6,13 +6,24 @@ branchname="$3"
 
 userpath="$path"
 if [ -d "$userpath" ]; then
-    pushd .
+    pushd . >/dev/null
     cd $userpath
-    mkdir -p doc
+    pwd
     git checkout master 2>/dev/null
-    ontime-commit "$duedate" 2>doc/ontime.error | gitbranchat "$branchname" 2>> doc/branch.error
-    if [ $(wc -c <doc/ontime.error) -gt 0 ]; then
-	echo "HEAD" | gitbranchat "$branchname" 2>> doc/branch.error
+    echo "checking out branch $branchname due at $duedate"
+    if ( git branch | grep "$branchname" ); then
+	git branch -D "$branchname" &>/dev/null
+	#git checkout "$branchname" &>/dev/null
+	#exit 0
     fi
-    popd
+    mkdir -p dkm_review
+    rm -f dkm_review/branch.error
+    ontime-commit "$duedate" 2>dkm_review/ontime.error | gitbranchat "$branchname" >/dev/null 2> >(grep -v "Already on " >> dkm_review/branch.error)
+    if [ $(wc -c <dkm_review/ontime.error) -gt 0 ]; then
+	echo "no ontime commit, checking out HEAD"
+	echo "HEAD" | gitbranchat "$branchname" 2>> dkm_review/branch.error
+    fi
+    popd >/dev/null
+else
+    echo "$userpath: no such directory" >&2
 fi
